-- HR Aura automation and trust-layer schema.
-- Run this in Supabase SQL editor after creating the project.

CREATE TABLE IF NOT EXISTS employees (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  employee_id TEXT,
  name TEXT,
  email TEXT,
  department TEXT,
  designation TEXT,
  status TEXT DEFAULT 'onboarding',
  performance_score NUMERIC DEFAULT 0,
  burnout_risk NUMERIC DEFAULT 0,
  blockchain_status TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id TEXT NOT NULL,
  date DATE NOT NULL,
  check_in TIMESTAMPTZ,
  check_out TIMESTAMPTZ,
  status TEXT DEFAULT 'present',
  productivity_score NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS leave_requests (
  id TEXT PRIMARY KEY,
  employee_id TEXT NOT NULL,
  leave_type TEXT NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  reason TEXT,
  status TEXT DEFAULT 'pending',
  ai_summary TEXT,
  blockchain_hash TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS onboarding_tasks (
  id TEXT PRIMARY KEY,
  employee_id TEXT NOT NULL,
  task_name TEXT NOT NULL,
  description TEXT,
  status TEXT DEFAULT 'pending',
  due_date DATE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS payroll_records (
  id TEXT PRIMARY KEY,
  workflow_id TEXT NOT NULL,
  employee_id TEXT NOT NULL,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  gross_salary NUMERIC NOT NULL,
  attendance_days NUMERIC DEFAULT 0,
  paid_leave_days NUMERIC DEFAULT 0,
  unpaid_leave_days NUMERIC DEFAULT 0,
  deductions JSONB DEFAULT '{}'::JSONB,
  net_salary NUMERIC NOT NULL,
  ai_summary TEXT NOT NULL,
  status TEXT DEFAULT 'approval_pending',
  blockchain_hash TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ai_workflows (
  id TEXT PRIMARY KEY,
  type TEXT NOT NULL,
  status TEXT NOT NULL,
  steps JSONB DEFAULT '[]'::JSONB,
  initiated_by TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS workflow_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workflow_id TEXT NOT NULL,
  type TEXT NOT NULL,
  status TEXT NOT NULL,
  step TEXT,
  message TEXT,
  payload JSONB DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS blockchain_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  hash TEXT NOT NULL,
  previous_hash TEXT NOT NULL,
  timestamp TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS chat_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role TEXT NOT NULL,
  content TEXT NOT NULL,
  metadata JSONB DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS approvals (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
  workflow_id TEXT,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  requested_by TEXT,
  approver_role TEXT DEFAULT 'manager',
  status TEXT DEFAULT 'pending',
  ai_summary TEXT,
  make_scenario_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE leave_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE onboarding_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE payroll_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_workflows ENABLE ROW LEVEL SECURITY;
ALTER TABLE workflow_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE blockchain_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE approvals ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "HR Aura read employees" ON employees;
DROP POLICY IF EXISTS "HR Aura read attendance" ON attendance;
DROP POLICY IF EXISTS "HR Aura read leave requests" ON leave_requests;
DROP POLICY IF EXISTS "HR Aura read onboarding tasks" ON onboarding_tasks;
DROP POLICY IF EXISTS "HR Aura read payroll records" ON payroll_records;
DROP POLICY IF EXISTS "HR Aura read workflows" ON ai_workflows;
DROP POLICY IF EXISTS "HR Aura read workflow events" ON workflow_events;
DROP POLICY IF EXISTS "HR Aura read blockchain logs" ON blockchain_logs;
DROP POLICY IF EXISTS "HR Aura read chat history" ON chat_history;
DROP POLICY IF EXISTS "HR Aura read approvals" ON approvals;
DROP POLICY IF EXISTS "HR Aura service insert employees" ON employees;
DROP POLICY IF EXISTS "HR Aura service insert attendance" ON attendance;
DROP POLICY IF EXISTS "HR Aura service insert leave requests" ON leave_requests;
DROP POLICY IF EXISTS "HR Aura service insert onboarding tasks" ON onboarding_tasks;
DROP POLICY IF EXISTS "HR Aura service insert payroll records" ON payroll_records;
DROP POLICY IF EXISTS "HR Aura service insert workflows" ON ai_workflows;
DROP POLICY IF EXISTS "HR Aura service insert workflow events" ON workflow_events;
DROP POLICY IF EXISTS "HR Aura service insert blockchain logs" ON blockchain_logs;
DROP POLICY IF EXISTS "HR Aura service insert chat history" ON chat_history;
DROP POLICY IF EXISTS "HR Aura service insert approvals" ON approvals;
DROP POLICY IF EXISTS "HR Aura service update workflows" ON ai_workflows;
DROP POLICY IF EXISTS "HR Aura service update approvals" ON approvals;
DROP POLICY IF EXISTS "HR Aura service update employees" ON employees;
DROP POLICY IF EXISTS "HR Aura service update leave requests" ON leave_requests;
DROP POLICY IF EXISTS "HR Aura service update onboarding tasks" ON onboarding_tasks;
DROP POLICY IF EXISTS "HR Aura service update payroll records" ON payroll_records;

CREATE POLICY "HR Aura read employees" ON employees FOR SELECT USING (true);
CREATE POLICY "HR Aura read attendance" ON attendance FOR SELECT USING (true);
CREATE POLICY "HR Aura read leave requests" ON leave_requests FOR SELECT USING (true);
CREATE POLICY "HR Aura read onboarding tasks" ON onboarding_tasks FOR SELECT USING (true);
CREATE POLICY "HR Aura read payroll records" ON payroll_records FOR SELECT USING (true);
CREATE POLICY "HR Aura read workflows" ON ai_workflows FOR SELECT USING (true);
CREATE POLICY "HR Aura read workflow events" ON workflow_events FOR SELECT USING (true);
CREATE POLICY "HR Aura read blockchain logs" ON blockchain_logs FOR SELECT USING (true);
CREATE POLICY "HR Aura read chat history" ON chat_history FOR SELECT USING (true);
CREATE POLICY "HR Aura read approvals" ON approvals FOR SELECT USING (true);

CREATE POLICY "HR Aura service insert employees" ON employees FOR INSERT WITH CHECK (true);
CREATE POLICY "HR Aura service insert attendance" ON attendance FOR INSERT WITH CHECK (true);
CREATE POLICY "HR Aura service insert leave requests" ON leave_requests FOR INSERT WITH CHECK (true);
CREATE POLICY "HR Aura service insert onboarding tasks" ON onboarding_tasks FOR INSERT WITH CHECK (true);
CREATE POLICY "HR Aura service insert payroll records" ON payroll_records FOR INSERT WITH CHECK (true);
CREATE POLICY "HR Aura service insert workflows" ON ai_workflows FOR INSERT WITH CHECK (true);
CREATE POLICY "HR Aura service insert workflow events" ON workflow_events FOR INSERT WITH CHECK (true);
CREATE POLICY "HR Aura service insert blockchain logs" ON blockchain_logs FOR INSERT WITH CHECK (true);
CREATE POLICY "HR Aura service insert chat history" ON chat_history FOR INSERT WITH CHECK (true);
CREATE POLICY "HR Aura service insert approvals" ON approvals FOR INSERT WITH CHECK (true);

CREATE POLICY "HR Aura service update workflows" ON ai_workflows FOR UPDATE USING (true);
CREATE POLICY "HR Aura service update approvals" ON approvals FOR UPDATE USING (true);
CREATE POLICY "HR Aura service update employees" ON employees FOR UPDATE USING (true);
CREATE POLICY "HR Aura service update leave requests" ON leave_requests FOR UPDATE USING (true);
CREATE POLICY "HR Aura service update onboarding tasks" ON onboarding_tasks FOR UPDATE USING (true);
CREATE POLICY "HR Aura service update payroll records" ON payroll_records FOR UPDATE USING (true);

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE ai_workflows;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE workflow_events;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE blockchain_logs;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE chat_history;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE approvals;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE payroll_records;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
